//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tata_win_resource.rc
//
#define IDD_TATASETUP                   101
#define IDI_TATAICON                    103
#define ID_PLAYNOSAVE                   1000
#define IDC_FULLSCREEN                  1001
#define IDC_RESOLUTION                  1002
#define IDC_VERTEXLIGHTING              1003
#define ID_PLAYNSAVE                    1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
